apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nascis
  name: nascis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nascis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nascis
    spec:
      containers:
      - name: nascis
        image: nascis/nascis:v1
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nascis
  labels:
    app.kubernetes.io/name: nascis
spec:
  selector:
    app.kubernetes.io/name: nascis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: web
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: nascis
spec:
    rules:
    - host: nascis.fr
      http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            serviceName: nascis
            servicePort: 80
